---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: partner
  namespace: {{ TNF_PARTNER_NAMESPACE }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: partner
  template:
    metadata:
      labels:
        app: partner
        test-network-function.com/generic: orchestrator
      annotations:
        test-network-function.com/defaultnetworkinterface: '"eth0"' # optional
        k8s.v1.cni.cncf.io/networks: macvlan-conf # multus network
      name: partner
    spec:
      containers:
        - command:
            - tail
            - -f
            - /dev/null
          image: "{{ TNF_PARTNER_REPO }}/cnf-test-partner:latest"
          name: partner
          resources:
            limits:
              memory: 512Mi
              cpu: 0.25
