---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tnfpartner
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tnfpartner
  template:
    metadata:
      labels:
        app: tnfpartner
        test-network-function.com/generic: orchestrator
      annotations:
        test-network-function.com/defaultnetworkinterface: '"eth0"' # optional
      name: tnfpartner
    spec:
      containers:
        - command:
            - tail
            - -f
            - /dev/null
          image: "{{ TNF_PARTNER_REPO }}/cnf-test-partner:latest"
          name: partner
          resources:
            limits:
              memory: 512Mi
              cpu: 0.25
