name: 'Test/push the `debug-partner` image'
on:
  # Run the workflow every day at 5 am UTC (1 am EST, 7am CET)
  # This is useful for keeping the image up-to-date with security
  # patches provided in the UBI.
  # Disclaimer: There is no guarantee that scheduled workflows will
  # run at the predefined time, if at all. The delay is usually
  # around 10-30 minutes.
  schedule:
    - cron: '0 5 * * *'
  release:
    types: [published]
  workflow_dispatch:

permissions: read-all

defaults:
  run:
    shell: bash
    working-directory: test-partner
env:
  REGISTRY: quay.io
  IMAGE_NAME: testnetworkfunction/debug-partner
  IMAGE_TAG: latest
  IMAGE_CONTAINER_FILE_PATH: test-partner/Dockerfile.debug-partner

jobs:
  test-debug-partner-image:
    name: 'Build and test the `debug-partner` image'
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3

      - name: 'Build the `debug-partner` image'
        run: docker build --no-cache -f Dockerfile.debug-partner -t $IMAGE_NAME:$IMAGE_TAG .

      - name: 'Test: Check if lscpu is installed'
        run: docker run $IMAGE_NAME:$IMAGE_TAG which lscpu

      - name: 'Test: Check if lsblk is installed'
        run: docker run $IMAGE_NAME:$IMAGE_TAG which lsblk

      - name: 'Test: Check if lspci is installed'
        run: docker run $IMAGE_NAME:$IMAGE_TAG which lspci

      - name: 'Test: Check if ping is installed'
        run: docker run $IMAGE_NAME:$IMAGE_TAG which ping

      - name: 'Test: Check if ip is installed'
        run: docker run $IMAGE_NAME:$IMAGE_TAG which ip

      - name: Authenticate against Quay.io
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: ${{ env.REGISTRY }}
          # Use a Robot Account to authenticate against Quay.io
          # https://docs.quay.io/glossary/robot-accounts.html
          username: ${{ secrets.QUAY_ROBOT_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - name: Add metadata
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          labels: |
            maintainer=certsuite maintainers
            org.opencontainers.image.title=Debug Partner
            org.opencontainers.image.description=CNF Certification Test uses it.
            org.opencontainers.image.vendor=certsuite
            name=debug-partner
            vendor=certsuite
          tags: |
            type=raw,value=latest
            type=schedule,pattern=nightly
            type=semver,pattern={{version}}

      - name: 'Build and push the new `debug-partner` image'
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6
        with:
          push: true
          file: ${{ env.IMAGE_CONTAINER_FILE_PATH }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha,scope=debug-partner
          cache-to: type=gha,mode=max,scope=debug-partner

      - name: If failed to create the image, send alert msg to dev team.
        if: ${{ failure() }}
        uses: ./.github/actions/slack-webhook-sender
        with:
          message: 'Failed to create debug parter image version ${{ env.IMAGE_TAG }}'
          slack_webhook: '${{ secrets.SLACK_ALERT_WEBHOOK_URL }}'
