name: 'Test multi-arch image builds on PRs'

on:
  pull_request:
    branches: [main]
    paths:
      - 'test-partner/Dockerfile*'
      - 'testapp/**'
      - '.github/workflows/pr-image-build.yaml'
  workflow_dispatch:

permissions: read-all

defaults:
  run:
    shell: bash

env:
  REGISTRY: quay.io
  SAMPLE_WORKLOAD_IMAGE_NAME: redhat-best-practices-for-k8s/certsuite-sample-workload
  DEBUG_PARTNER_IMAGE_NAME: testnetworkfunction/debug-partner
  IMAGE_TAG: pr-test

jobs:
  build-sample-workload-image:
    name: 'Build multi-arch `certsuite-sample-workload` image'
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3

      - name: Setup Docker Storage
        uses: ./.github/actions/setup-docker-storage

      - name: 'Build multi-arch `certsuite-sample-workload` image (no push)'
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6
        with:
          push: false
          file: ./test-partner/Dockerfile
          tags: '${{ env.SAMPLE_WORKLOAD_IMAGE_NAME }}:${{ env.IMAGE_TAG }}'
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha,scope=certsuite-sample-workload-pr
          cache-to: type=gha,mode=max,scope=certsuite-sample-workload-pr

  build-debug-partner-image:
    name: 'Build multi-arch `debug-partner` image'
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3

      - name: Setup Docker Storage
        uses: ./.github/actions/setup-docker-storage

      - name: 'Build multi-arch `debug-partner` image (no push)'
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6
        with:
          push: false
          file: ./test-partner/Dockerfile.debug-partner
          tags: '${{ env.DEBUG_PARTNER_IMAGE_NAME }}:${{ env.IMAGE_TAG }}'
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha,scope=debug-partner-pr
          cache-to: type=gha,mode=max,scope=debug-partner-pr
